apiVersion: apps/v1
kind: Deployment
metadata:
  name: terra-backend
  labels:
    app: terra-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terra-backend
  template:
    metadata:
      labels:
        app: terra-backend
    spec:
      containers:
      - name: terra-backend
        image: terra-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@terra-db:5432/terradb
---
apiVersion: v1
kind: Service
metadata:
  name: terra-backend
spec:
  selector:
    app: terra-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP