apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terra-db
spec:
  serviceName: "terra-db"
  replicas: 1
  selector:
    matchLabels:
      app: terra-db
  template:
    metadata:
      labels:
        app: terra-db
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: terradb
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: terra-db
spec:
  selector:
    app: terra-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None