// frontend/src/store/actions/types.js

// Authentication action types
export const AUTH_TYPES = {
    AUTH_LOADING: 'AUTH_LOADING',
    USER_LOADED: 'USER_LOADED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    AUTH_ERROR: 'AUTH_ERROR',
    CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS'
};

// UI action types
export const UI_TYPES = {
    SET_LOADING: 'SET_LOADING',
    CLEAR_LOADING: 'CLEAR_LOADING',
    ADD_TOAST: 'ADD_TOAST',
    REMOVE_TOAST: 'REMOVE_TOAST'
};

// Route action types
export const ROUTE_TYPES = {
    GET_ROUTES: 'GET_ROUTES',
    GET_ROUTE: 'GET_ROUTE',
    ADD_ROUTE: 'ADD_ROUTE',
    UPDATE_ROUTE: 'UPDATE_ROUTE',
    DELETE_ROUTE: 'DELETE_ROUTE',
    ROUTE_ERROR: 'ROUTE_ERROR',
    CLEAR_ROUTE: 'CLEAR_ROUTE',
    SET_ROUTE_LOADING: 'SET_ROUTE_LOADING',
    GET_PUBLIC_ROUTES: 'GET_PUBLIC_ROUTES'
};